import type { LevelDefinition } from '../level-mode/LevelTypes';

export const levels: LevelDefinition[] = [
  {
    id: 'lvl-1',
    name: '新手之路',
    boardW: 6,
    boardH: 6,
    cellSize: 64,
    pieces: [
      { id: 'p1', type: 'A', x: 0, y: 0 },
      { id: 'p2', type: 'B', x: 1, y: 2 },
      { id: 'p3', type: 'C', x: 4, y: 4 },
    ],
    targets: [
      { id: 't1', targetType: 'A', x: 5, y: 0 },
      { id: 't2', targetType: 'B', x: 5, y: 3 },
      { id: 't3', targetType: 'C', x: 2, y: 5 },
    ],
    obstacles: [
      { id: 'o1', x: 2, y: 2 },
      { id: 'o2', x: 3, y: 2 },
      { id: 'o3', x: 2, y: 3 },
    ],
  },
  {
    id: 'lvl-2',
    name: '双线穿梭',
    boardW: 6,
    boardH: 6,
    cellSize: 64,
    pieces: [
      { id: 'p1', type: 'A', x: 1, y: 4 },
      { id: 'p2', type: 'B', x: 4, y: 1 },
      { id: 'p3', type: 'C', x: 0, y: 2 },
    ],
    targets: [
      { id: 't1', targetType: 'A', x: 5, y: 5 },
      { id: 't2', targetType: 'B', x: 0, y: 0 },
      { id: 't3', targetType: 'C', x: 3, y: 3 },
    ],
    obstacles: [
      { id: 'o1', x: 2, y: 1 },
      { id: 'o2', x: 2, y: 2 },
      { id: 'o3', x: 2, y: 3 },
      { id: 'o4', x: 3, y: 1 },
    ],
  },
  {
    id: 'lvl-3',
    name: '回字迷阵',
    boardW: 6,
    boardH: 6,
    cellSize: 64,
    pieces: [
      { id: 'p1', type: 'A', x: 0, y: 5 },
      { id: 'p2', type: 'B', x: 5, y: 0 },
      { id: 'p3', type: 'C', x: 1, y: 1 },
      { id: 'p4', type: 'D', x: 4, y: 4 },
    ],
    targets: [
      { id: 't1', targetType: 'A', x: 5, y: 5 },
      { id: 't2', targetType: 'B', x: 0, y: 0 },
      { id: 't3', targetType: 'C', x: 4, y: 1 },
      { id: 't4', targetType: 'D', x: 1, y: 4 },
    ],
    obstacles: [
      { id: 'o1', x: 2, y: 1 },
      { id: 'o2', x: 3, y: 1 },
      { id: 'o3', x: 2, y: 2 },
      { id: 'o4', x: 3, y: 2 },
      { id: 'o5', x: 2, y: 3 },
      { id: 'o6', x: 3, y: 3 },
      { id: 'o7', x: 2, y: 4 },
      { id: 'o8', x: 3, y: 4 },
    ],
  },
  {
    id: 'lvl-4',
    name: '交叉风暴',
    boardW: 6,
    boardH: 6,
    cellSize: 64,
    pieces: [
      { id: 'p1', type: 'A', x: 0, y: 1 },
      { id: 'p2', type: 'B', x: 5, y: 4 },
      { id: 'p3', type: 'C', x: 2, y: 0 },
      { id: 'p4', type: 'D', x: 3, y: 5 },
    ],
    targets: [
      { id: 't1', targetType: 'A', x: 5, y: 1 },
      { id: 't2', targetType: 'B', x: 0, y: 4 },
      { id: 't3', targetType: 'C', x: 2, y: 5 },
      { id: 't4', targetType: 'D', x: 3, y: 0 },
    ],
    obstacles: [
      { id: 'o1', x: 1, y: 2 },
      { id: 'o2', x: 2, y: 2 },
      { id: 'o3', x: 3, y: 2 },
      { id: 'o4', x: 4, y: 2 },
      { id: 'o5', x: 1, y: 3 },
      { id: 'o6', x: 2, y: 3 },
      { id: 'o7', x: 3, y: 3 },
      { id: 'o8', x: 4, y: 3 },
    ],
  },
  {
    id: 'lvl-5',
    name: '终极收集',
    boardW: 6,
    boardH: 6,
    cellSize: 64,
    pieces: [
      { id: 'p1', type: 'A', x: 0, y: 0 },
      { id: 'p2', type: 'B', x: 5, y: 0 },
      { id: 'p3', type: 'C', x: 0, y: 5 },
      { id: 'p4', type: 'D', x: 5, y: 5 },
      { id: 'p5', type: 'E', x: 2, y: 2 },
    ],
    targets: [
      { id: 't1', targetType: 'A', x: 3, y: 0 },
      { id: 't2', targetType: 'B', x: 2, y: 5 },
      { id: 't3', targetType: 'C', x: 5, y: 2 },
      { id: 't4', targetType: 'D', x: 0, y: 3 },
      { id: 't5', targetType: 'E', x: 3, y: 3 },
    ],
    obstacles: [
      { id: 'o1', x: 1, y: 1 },
      { id: 'o2', x: 2, y: 1 },
      { id: 'o3', x: 3, y: 1 },
      { id: 'o4', x: 4, y: 1 },
      { id: 'o5', x: 1, y: 4 },
      { id: 'o6', x: 2, y: 4 },
      { id: 'o7', x: 3, y: 4 },
      { id: 'o8', x: 4, y: 4 },
    ],
  },
];
